[["/usr/local/lib/python3.10/dist-packages/h11/__init__.py",[false,[["Connection",true,2,["Connection","/usr/local/lib/python3.10/dist-packages/h11/_connection.py",5]],["NEED_DATA",true,2,["NEED_DATA","/usr/local/lib/python3.10/dist-packages/h11/_connection.py",5]],["PAUSED",true,2,["PAUSED","/usr/local/lib/python3.10/dist-packages/h11/_connection.py",5]],["ConnectionClosed",true,2,["ConnectionClosed","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["Data",true,2,["Data","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["EndOfMessage",true,2,["EndOfMessage","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["Event",true,2,["Event","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["InformationalResponse",true,2,["InformationalResponse","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["Request",true,2,["Request","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["Response",true,2,["Response","/usr/local/lib/python3.10/dist-packages/h11/_events.py",5]],["CLIENT",true,2,["CLIENT","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["CLOSED",true,2,["CLOSED","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["DONE",true,2,["DONE","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["ERROR",true,2,["ERROR","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["IDLE",true,2,["IDLE","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["MUST_CLOSE",true,2,["MUST_CLOSE","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["SEND_BODY",true,2,["SEND_BODY","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["SEND_RESPONSE",true,2,["SEND_RESPONSE","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["SERVER",true,2,["SERVER","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["SWITCHED_PROTOCOL",true,2,["SWITCHED_PROTOCOL","/usr/local/lib/python3.10/dist-packages/h11/_state.py",5]],["LocalProtocolError",true,2,["LocalProtocolError","/usr/local/lib/python3.10/dist-packages/h11/_util.py",5]],["ProtocolError",true,2,["ProtocolError","/usr/local/lib/python3.10/dist-packages/h11/_util.py",5]],["RemoteProtocolError",true,2,["RemoteProtocolError","/usr/local/lib/python3.10/dist-packages/h11/_util.py",5]],["PRODUCT_ID",true,14,null],["__all__",true,13,null]]]]]